[package]
name = "app_routes"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Application routes for Rust/UI."
repository = "https://github.com/rust-ui/ui"
readme = "../../README.md"
keywords = ["dioxus", "ui", "routing"]
categories = ["gui", "web-programming"]

[lints]
workspace = true

[dependencies]
strum.workspace = true
heck.workspace = true
