// AUTO-GENERATED by build_registry_v2_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_v2_dioxus/Cargo.toml` to regenerate.

#![allow(
    clippy::must_use_candidate,
    clippy::missing_const_for_fn,
    clippy::missing_errors_doc,
    clippy::uninlined_format_args,
    clippy::derive_partial_eq_without_eq,
    clippy::option_if_let_else,
    clippy::enum_variant_names
)]

pub mod all_blocks;
pub mod demos_sidenav;
pub mod my_command_bar_constants;
pub mod sidenav_get_started;
pub mod sidenav_hooks;
pub mod source_map;
pub mod static_md_registry;
pub mod all_workflows;
