pub mod md_header;
pub mod md_prev_next;
pub mod md_shared_with_toc;
pub mod md_skeleton;
pub mod my_resizable;
pub mod resizable_wrapper;
pub mod static_demo_wrapper;
pub mod static_install_wrapper;
pub mod static_md_docs_wrapper;
