#!/bin/bash
# ---------------------------------------------------------------------------
# WORKAROUND for dioxus-cli bug: `dx` never bakes an AppIcon into the built
# .app bundle on iOS (Dioxus.toml's [bundle].icon key is silently ignored —
# same class of bug as dioxuslabs/dioxus#3685, open on Android, confirmed
# here on iOS too: every `.app`/`.ipa` dx produces has zero Assets.car /
# AppIcon.appiconset in it). Without this, the simulator shows the generic
# grid placeholder instead of the Rust/UI "R" logo.
#
# This script takes the .app bundle dx just built, compiles
# ios/Assets.xcassets/ (generated by ios/generate_ios_icon_set.sh) into a
# real Assets.car via `actool` — the same compiler Xcode uses — and drops it
# straight into the bundle, then merges the resulting CFBundleIcons keys into
# the bundle's Info.plist.
#
# Usage: ios/inject_app_icon.sh /path/to/DioxusUi.app
#
# LIMITATION: dx serve rebuilds/reinstalls the app on every hot-reload
# trigger and does not know about this patch, so it can wipe it out again.
# If the icon reverts to the placeholder mid dx-serve session, just stop dx,
# rerun the run_ios_*.sh script (which re-injects before launching).
# ---------------------------------------------------------------------------

set -e

if [ -z "$1" ] || [ ! -d "$1" ]; then
  echo "⚠️  Usage: $0 /path/to/Foo.app (bundle not found: '$1')"
  exit 1
fi
APP_BUNDLE="$(cd "$1" && pwd)"

cd "$(dirname "$0")"
WORKDIR=$(mktemp -d)
trap 'rm -rf "$WORKDIR"' EXIT

echo "🎨 Compiling AppIcon.appiconset via actool..."
xcrun actool \
  --compile "$WORKDIR" \
  --platform iphonesimulator \
  --minimum-deployment-target 16.0 \
  --app-icon AppIcon \
  --output-partial-info-plist "$WORKDIR/partial-info.plist" \
  Assets.xcassets \
  > /dev/null

if [ ! -f "$WORKDIR/Assets.car" ]; then
  echo "⚠️  actool did not produce Assets.car — icon injection skipped"
  exit 1
fi

cp "$WORKDIR/Assets.car" "$APP_BUNDLE/Assets.car"

# Merge CFBundleIcons / CFBundleIconName from the partial plist actool
# produced into the app's real Info.plist (dx's Info.plist only sets
# CFBundleIconName = "AppIcon" with no matching asset — this is what fixes
# that dangling reference).
/usr/libexec/PlistBuddy -c "Merge $WORKDIR/partial-info.plist" "$APP_BUNDLE/Info.plist" 2>/dev/null || true

echo "✅ Icon injected into $APP_BUNDLE"
