// AUTO-GENERATED by build_registry_v2_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_v2_dioxus/Cargo.toml` to regenerate.

pub mod md_docs;
pub mod types;
