use std::sync::Arc;

use app_domain::markdown_config::registry_entry::RegistryEntry;

// * This file was generated automatically with build_registry.

pub fn get_all_arc_demos_for_components() -> Vec<(&'static str, Arc<Vec<RegistryEntry>>)> {
    vec![
        ("Get Started", Arc::new(SHARED_GET_STARTED.to_vec())),
        ("Components", Arc::new(ALL_SIDENAV_COMPONENTS.to_vec())),
    ]
}

pub fn get_all_arc_demos_for_hooks() -> Vec<(&'static str, Arc<Vec<RegistryEntry>>)> {
    vec![("Get Started", Arc::new(SHARED_GET_STARTED.to_vec())), ("Hooks", Arc::new(ALL_SIDENAV_HOOKS.to_vec()))]
}

/* ========================================================== */
/*                     ✨ CONSTANTS ✨                        */
/* ========================================================== */

const SHARED_GET_STARTED: &[RegistryEntry] = &[
    RegistryEntry {
        title: "Introduction",
        path_url: "introduction",
        path_md: "public/docs/introduction.md",
        description: "The idea behind Rust/UI is to provide developers with the right tools to build Rust fullstack applications.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: Some(1),
    },
    RegistryEntry {
        title: "Installation",
        path_url: "installation",
        path_md: "public/docs/installation.md",
        description: "Get started with Rust/UI by installing the CLI tool and setting up your project with minimal dependencies and framework support.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: Some(2),
    },
    RegistryEntry {
        title: "CLI",
        path_url: "cli",
        path_md: "public/docs/cli.md",
        description: "Learn how to use the Rust/UI CLI to install components, initialize projects, and manage your component library efficiently.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: Some(3),
    },
    RegistryEntry {
        title: "Icons",
        path_url: "icons",
        path_md: "public/docs/icons.md",
        description: "Beautiful SVG icons for Rust applications. 1,600+ Lucide icons with full Leptos and Dioxus support, Tailwind CSS integration, and zero dependencies.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: Some(4),
    },
    RegistryEntry {
        title: "Figma",
        path_url: "figma",
        path_md: "public/docs/figma.md",
        description: "Coming soon.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: Some(5),
    },
    RegistryEntry {
        title: "Changelog",
        path_url: "changelog",
        path_md: "public/docs/changelog.md",
        description: "Latest updates and announcements.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: Some(99),
    },
];

pub const ALL_SIDENAV_COMPONENTS: &[RegistryEntry] = &[
    RegistryEntry {
        title: "Accordion",
        path_url: "accordion",
        path_md: "public/docs/components/accordion.md",
        description: "Rust/UI component that displays an Accordion.",
        tags: &["accordion"],
        image: "/images/thumbnails/accordion.webp",
        image_dark: "/images/thumbnails/accordion-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Alert",
        path_url: "alert",
        path_md: "public/docs/components/alert.md",
        description: "Rust/UI component that displays a callout to the user.",
        tags: &[],
        image: "/images/thumbnails/alert.webp",
        image_dark: "/images/thumbnails/alert-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Alert Dialog",
        path_url: "alert-dialog",
        path_md: "public/docs/components/alert-dialog.md",
        description: "Rust/UI component that displays a modal dialog that interrupts the user with important content and expects a response.",
        tags: &["dialog"],
        image: "/images/thumbnails/dialog.webp",
        image_dark: "/images/thumbnails/dialog-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Animate",
        path_url: "animate",
        path_md: "public/docs/components/animate.md",
        description: "A wrapper for animations, made with Tailwind CSS. Works seamlessly with any children component.",
        tags: &["animation"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Animate Group",
        path_url: "animate-group",
        path_md: "public/docs/components/animate-group.md",
        description: "A wrapper for animations, made with Tailwind CSS. Works seamlessly with any children component.",
        tags: &["animation"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Aspect Ratio",
        path_url: "aspect_ratio",
        path_md: "public/docs/components/aspect_ratio.md",
        description: "Displays content within a desired ratio.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "AutoForm",
        path_url: "auto-form",
        path_md: "public/docs/components/auto-form.md",
        description: "Automatically generate form UI from Rust structs using a derive macro with built-in validation support.",
        tags: &["input"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Avatar",
        path_url: "avatar",
        path_md: "public/docs/components/avatar.md",
        description: "Rust/UI component that displays an avatar with image and fallback support.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Badge",
        path_url: "badge",
        path_md: "public/docs/components/badge.md",
        description: "Rust/UI component that displays a badge or a component that looks like a badge.",
        tags: &[],
        image: "/images/thumbnails/badge.webp",
        image_dark: "/images/thumbnails/badge-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Bottom Nav",
        path_url: "bottom-nav",
        path_md: "public/docs/components/bottom-nav.md",
        description: "Rust/UI component that displays a mobile-friendly bottom navigation bar.",
        tags: &["navigation"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Breadcrumb",
        path_url: "breadcrumb",
        path_md: "public/docs/components/breadcrumb.md",
        description: "Rust/UI component that displays the path to the current resource using a hierarchy of links.",
        tags: &["navigation"],
        image: "/images/thumbnails/breadcrumb.webp",
        image_dark: "/images/thumbnails/breadcrumb-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Button",
        path_url: "button",
        path_md: "public/docs/components/button.md",
        description: "Rust/UI component that displays a button or a component that looks like a button.",
        tags: &["button"],
        image: "/images/thumbnails/button.webp",
        image_dark: "/images/thumbnails/button-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Button Action",
        path_url: "button-action",
        path_md: "public/docs/components/button-action.md",
        description: "A button that requires press-and-hold to activate, showing a progress indicator.",
        tags: &[],
        image: "/images/thumbnails/button.webp",
        image_dark: "/images/thumbnails/button-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Button Group",
        path_url: "button-group",
        path_md: "public/docs/components/button-group.md",
        description: "A component that groups multiple buttons together with shared borders and styling.",
        tags: &["button"],
        image: "/images/thumbnails/button.webp",
        image_dark: "/images/thumbnails/button-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Callout",
        path_url: "callout",
        path_md: "public/docs/components/callout.md",
        description: "A styled alert block for docs and rich content, with Default, Info, and Warning variants.",
        tags: &["utils"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Card",
        path_url: "card",
        path_md: "public/docs/components/card.md",
        description: "Rust/UI component that displays a card with header, content and footer.",
        tags: &["card"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Card Carousel",
        path_url: "card-carousel",
        path_md: "public/docs/components/card-carousel.md",
        description: "Rust/UI component that displays a card similar as Airbnb Card.",
        tags: &["card"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Carousel",
        path_url: "carousel",
        path_md: "public/docs/components/carousel.md",
        description: "Rust/UI component for cycling through elements — slides, images, or cards — with prev/next navigation.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Checkbox",
        path_url: "checkbox",
        path_md: "public/docs/components/checkbox.md",
        description: "Rust/UI component that displays a control that allows the user to toggle between checked and not checked.",
        tags: &["utils"],
        image: "/images/thumbnails/checkbox.webp",
        image_dark: "/images/thumbnails/checkbox-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Chips",
        path_url: "chips",
        path_md: "public/docs/components/chips.md",
        description: "Rust/UI component that displays a chip or a component that looks like a chip.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Collapsible",
        path_url: "collapsible",
        path_md: "public/docs/components/collapsible.md",
        description: "An interactive component which expands/collapses a panel with smooth animation.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Combobox",
        path_url: "combobox",
        path_md: "public/docs/components/combobox.md",
        description: "Autocomplete input and command palette with a list of suggestions.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Command",
        path_url: "command",
        path_md: "public/docs/components/command.md",
        description: "Fast, composable, unstyled command menu for Leptos.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Context Menu",
        path_url: "context-menu",
        path_md: "public/docs/components/context-menu.md",
        description: "Rust/UI component that displays a context menu on right-click.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Data Table",
        path_url: "data-table",
        path_md: "public/docs/components/data-table.md",
        description: "Powerful data table with advanced features including filtering, sorting, column visibility, and row selection.",
        tags: &["table"],
        image: "/images/thumbnails/table.webp",
        image_dark: "/images/thumbnails/table-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Date Picker",
        path_url: "date-picker",
        path_md: "public/docs/components/date-picker.md",
        description: "Rust/UI component that displays a date picker.",
        tags: &[],
        image: "/images/thumbnails/date-picker.webp",
        image_dark: "/images/thumbnails/date-picker-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Dialog",
        path_url: "dialog",
        path_md: "public/docs/components/dialog.md",
        description: "Rust/UI component that displays a modal dialog that the user can interact with.",
        tags: &["dialog"],
        image: "/images/thumbnails/dialog.webp",
        image_dark: "/images/thumbnails/dialog-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Direction Provider",
        path_url: "direction-provider",
        path_md: "public/docs/components/direction-provider.md",
        description: "Rust/UI wrapper component that sets text direction (LTR or RTL) for all children, enabling right-to-left layout support.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Drag and Drop",
        path_url: "drag-and-drop",
        path_md: "public/docs/components/drag-and-drop.md",
        description: "Rust/UI component that allows users to drag and drop elements.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Drawer",
        path_url: "drawer",
        path_md: "public/docs/components/drawer.md",
        description: "A Drawer for Rust. Inspired by the amazing work of Emil Kowalski.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Dropdown Menu",
        path_url: "dropdown-menu",
        path_md: "public/docs/components/dropdown-menu.md",
        description: "Rust/UI component that displays a dropdown menu.",
        tags: &["dropdown"],
        image: "/images/thumbnails/dropdown.webp",
        image_dark: "/images/thumbnails/dropdown-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Dropzone",
        path_url: "dropzone",
        path_md: "public/docs/components/dropzone.md",
        description: "Rust/UI component that allows you to drop files onto it.",
        tags: &["utils"],
        image: "/images/thumbnails/dropzone.webp",
        image_dark: "/images/thumbnails/dropzone-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Empty",
        path_url: "empty",
        path_md: "public/docs/components/empty.md",
        description: "Use the Empty component to display a empty state.",
        tags: &[],
        image: "/images/thumbnails/button.webp",
        image_dark: "/images/thumbnails/button-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Field",
        path_url: "field",
        path_md: "public/docs/components/field.md",
        description: "Rust/UI components for composing accessible form fields with labels, descriptions, and error messages.",
        tags: &["input"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Form",
        path_url: "form",
        path_md: "public/docs/components/form.md",
        description: "Rust/UI components for building accessible forms with labels, descriptions, and error messages.",
        tags: &["input"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Hover Card",
        path_url: "hover-card",
        path_md: "public/docs/components/hover-card.md",
        description: "Rust/UI component that displays rich content in a floating card when hovering over a trigger element.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Input",
        path_url: "input",
        path_md: "public/docs/components/input.md",
        description: "Rust/UI component that displays an input field that allows the user to enter text.",
        tags: &["input"],
        image: "/images/thumbnails/input.webp",
        image_dark: "/images/thumbnails/input-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Input Group",
        path_url: "input-group",
        path_md: "public/docs/components/input-group.md",
        description: "A component that combines inputs with addons like icons, text, or buttons.",
        tags: &["input"],
        image: "/images/thumbnails/input.webp",
        image_dark: "/images/thumbnails/input-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Input OTP",
        path_url: "input-otp",
        path_md: "public/docs/components/input-otp.md",
        description: "Rust/UI component that displays an OTP input.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Input Phone",
        path_url: "input-phone",
        path_md: "public/docs/components/input-phone.md",
        description: "Rust/UI component that displays a phone number input with country code selector and automatic formatting.",
        tags: &["input"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Item",
        path_url: "item",
        path_md: "public/docs/components/item.md",
        description: "A flexible container component for displaying list items with media, content, and actions.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Kbd",
        path_url: "kbd",
        path_md: "public/docs/components/kbd.md",
        description: "Display keyboard shortcuts and key combinations with proper styling.",
        tags: &["utils"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Label",
        path_url: "label",
        path_md: "public/docs/components/label.md",
        description: "Rust/UI component that displays a label for an input field.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Marquee",
        path_url: "marquee",
        path_md: "public/docs/components/marquee.md",
        description: "Rust/UI component that displays an infinite scrolling component that can be used to display text, images, or videos.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Menubar",
        path_url: "menubar",
        path_md: "public/docs/components/menubar.md",
        description: "Rust/UI component that displays a horizontal menu bar with dropdown menus, submenus, checkboxes, and radio items.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "MultiSelect",
        path_url: "multi-select",
        path_md: "public/docs/components/multi-select.md",
        description: "Rust/UI component that displays a dropdown menu that allows the user to select several options.",
        tags: &["select"],
        image: "/images/thumbnails/select.webp",
        image_dark: "/images/thumbnails/select-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Navigation Menu",
        path_url: "navigation_menu",
        path_md: "public/docs/components/navigation_menu.md",
        description: "Rust/UI component for site-level horizontal navigation with animated dropdown panels and hover-activated content.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Pagination",
        path_url: "pagination",
        path_md: "public/docs/components/pagination.md",
        description: "Rust/UI component that displays a pagination component.",
        tags: &["navigation"],
        image: "/images/thumbnails/pagination.webp",
        image_dark: "/images/thumbnails/pagination-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Popover",
        path_url: "popover",
        path_md: "public/docs/components/popover.md",
        description: "Rust/UI component that displays rich content in a portal, triggered by a button.",
        tags: &["popover"],
        image: "/images/thumbnails/popover.webp",
        image_dark: "/images/thumbnails/popover-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Pressable",
        path_url: "pressable",
        path_md: "public/docs/components/pressable.md",
        description: "Wrapper component that adds press feedback (scale effect) to any children.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Progress",
        path_url: "progress",
        path_md: "public/docs/components/progress.md",
        description: "Rust/UI component that displays a progress bar indicating task completion.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Radio Button",
        path_url: "radio-button",
        path_md: "public/docs/components/radio-button.md",
        description: "Rust/UI component that displays a set of checkable buttons where only one can be selected at a time.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Radio Button Group",
        path_url: "radio-button-group",
        path_md: "public/docs/components/radio-button-group.md",
        description: "Rust/UI component that displays a group of radio buttons.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Scroll Area",
        path_url: "scroll-area",
        path_md: "public/docs/components/scroll-area.md",
        description: "Rust/UI component that provides custom scrolling functionality with cross-browser styling.",
        tags: &["utils"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Select",
        path_url: "select",
        path_md: "public/docs/components/select.md",
        description: "Rust/UI component that displays a dropdown menu that allows the user to select an option.",
        tags: &["select"],
        image: "/images/thumbnails/select.webp",
        image_dark: "/images/thumbnails/select-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Separator",
        path_url: "separator",
        path_md: "public/docs/components/separator.md",
        description: "Rust/UI component that displays a separator line.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Sheet",
        path_url: "sheet",
        path_md: "public/docs/components/sheet.md",
        description: "Rust/UI component that displays a sheet.",
        tags: &["navigation"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Shimmer",
        path_url: "shimmer",
        path_md: "public/docs/components/shimmer.md",
        description: "Auto-adapting skeleton loader that mirrors your DOM structure.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Skeleton",
        path_url: "skeleton",
        path_md: "public/docs/components/skeleton.md",
        description: "Rust/UI component that show a placeholder while content is loading.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Slider",
        path_url: "slider",
        path_md: "public/docs/components/slider.md",
        description: "Rust/UI component that allows users to select a value from a range.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Sonner",
        path_url: "sonner",
        path_md: "public/docs/components/sonner.md",
        description: "Rust/UI Toast, inspired by Sonner.",
        tags: &[],
        image: "/images/thumbnails/toast.webp",
        image_dark: "/images/thumbnails/toast-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Spinner",
        path_url: "spinner",
        path_md: "public/docs/components/spinner.md",
        description: "A loading spinner component with animation for indicating processing states.",
        tags: &["animation", "utils"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Status",
        path_url: "status",
        path_md: "public/docs/components/status.md",
        description: "Rust/UI component for displaying statuses.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Switch",
        path_url: "switch",
        path_md: "public/docs/components/switch.md",
        description: "Rust/UI component that displays a control that allows the user to toggle between checked and not checked.",
        tags: &["utils"],
        image: "/images/thumbnails/switch.webp",
        image_dark: "/images/thumbnails/switch-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Table",
        path_url: "table",
        path_md: "public/docs/components/table.md",
        description: "Rust/UI component that displays a table with header, body and footer.",
        tags: &["table"],
        image: "/images/thumbnails/table.webp",
        image_dark: "/images/thumbnails/table-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Tabs",
        path_url: "tabs",
        path_md: "public/docs/components/tabs.md",
        description: "Rust/UI component that displays a set of layered sections of content, known as tab pages, that are displayed one at a time.",
        tags: &["utils"],
        image: "/images/thumbnails/tabs.webp",
        image_dark: "/images/thumbnails/tabs-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Textarea",
        path_url: "textarea",
        path_md: "public/docs/components/textarea.md",
        description: "Rust/UI component that displays a textarea.",
        tags: &["input"],
        image: "/images/thumbnails/textarea.webp",
        image_dark: "/images/thumbnails/textarea-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Theme Toggle",
        path_url: "theme-toggle",
        path_md: "public/docs/components/theme-toggle.md",
        description: "A sleek theme toggle component that smoothly transitions between light and dark modes with animated sun and moon icons.",
        tags: &["button", "animation"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Toast",
        path_url: "toast",
        path_md: "public/docs/components/toast.md",
        description: "Rust/UI component that displays toast notifications.",
        tags: &[],
        image: "/images/thumbnails/toast.webp",
        image_dark: "/images/thumbnails/toast-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Toggle Group",
        path_url: "toggle-group",
        path_md: "public/docs/components/toggle-group.md",
        description: "A set of toggle buttons that can be used to group related options.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Tooltip",
        path_url: "tooltip",
        path_md: "public/docs/components/tooltip.md",
        description: "A popup component that displays informative text when users hover over, focus on, or click an element.",
        tags: &["dialog"],
        image: "/images/thumbnails/tooltip.webp",
        image_dark: "/images/thumbnails/tooltip-dark.webp",
        is_new: false,
        order: None,
    },
];

pub const ALL_SIDENAV_HOOKS: &[RegistryEntry] = &[
    RegistryEntry {
        title: "Use Copy Clipboard",
        path_url: "use-copy-clipboard",
        path_md: "public/docs/hooks/use-copy-clipboard.md",
        description: "A Rust/UI hook that copies text to clipboard with optional timeout to show copied state.",
        tags: &["utils"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Use History",
        path_url: "use-history",
        path_md: "public/docs/hooks/use-history.md",
        description: "Undo/redo history stack for URL-based state, with keyboard shortcuts (⌘Z / ⌘⇧Z).",
        tags: &["utils"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Use Horizontal Scroll",
        path_url: "use-horizontal-scroll",
        path_md: "public/docs/hooks/use-horizontal-scroll.md",
        description: "A Rust/UI hook that manages horizontal scrolling with state tracking and programmatic scroll controls.",
        tags: &["utils"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Use Is Mobile",
        path_url: "use-is-mobile",
        path_md: "public/docs/hooks/use-is-mobile.md",
        description: "A reactive hook that returns true when the viewport is below the mobile breakpoint (768px).",
        tags: &["utils"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Use Lock Body Scroll",
        path_url: "use-lock-body-scroll",
        path_md: "public/docs/hooks/use-lock-body-scroll.md",
        description: "A Rust/UI hook that locks and unlocks body scrolling, useful for modal dialogs, sheets, and overlays.",
        tags: &["utils", "dialog"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
    RegistryEntry {
        title: "Use Locks",
        path_url: "use-locks",
        path_md: "public/docs/hooks/use-locks.md",
        description: "Context hook for locking design params against randomization — each param can be individually toggled.",
        tags: &["utils"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Use Media Query",
        path_url: "use-media-query",
        path_md: "public/docs/hooks/use-media-query.md",
        description: "A reactive hook that tracks whether a CSS media query matches, updating automatically when the viewport changes.",
        tags: &["utils"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Use Press Hold",
        path_url: "use-press-hold",
        path_md: "public/docs/hooks/use-press-hold.md",
        description: "A Rust/UI hook for press-and-hold interactions with animated progress.",
        tags: &[],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: true,
        order: None,
    },
    RegistryEntry {
        title: "Use Random",
        path_url: "use-random",
        path_md: "public/docs/hooks/use-random.md",
        description: "A Rust/UI hook that generates unique random IDs for DOM elements and CSS animations.",
        tags: &["utils", "animation", "css"],
        image: "/images/thumbnails/_placeholder.webp",
        image_dark: "/images/thumbnails/_placeholder-dark.webp",
        is_new: false,
        order: None,
    },
];
